kind: Service
apiVersion: v1
metadata:
  labels:
    app: agcoelba
  name: agcoelba
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: agcoelba
  type: NodePort