kind: Service
apiVersion: v1
metadata:
  labels:
    app: agelektro
  name: agelektro
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: agelektro
  type: NodePort
