apiVersion: v2
name: agencia-virtual
description: Helm chart para deployar o Agencia Virtual
type: application
version: 0.1.0
appVersion: "0.3.0"
icon: https://tc.com.br/wp-content/uploads/2021/06/coelba-bolsa.png